# Generated by Django 4.0.6 on 2022-07-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='Img',
            field=models.ImageField(default='d.jpg', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='click',
            name='ip',
            field=models.GenericIPAddressField(default='000.000.0.0'),
        ),
        migrations.AlterField(
            model_name='view',
            name='ip',
            field=models.GenericIPAddressField(default='000.000.0.0'),
        ),
    ]
