# Generated by Django 4.0.6 on 2022-07-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdManagement', '0002_alter_ad_img_alter_click_ip_alter_view_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='Img',
            field=models.ImageField(default='de.jpg', upload_to='img/'),
        ),
    ]
